# Generated by Django 5.0.6 on 2024-05-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("edition", models.PositiveIntegerField()),
                ("publication_year", models.PositiveIntegerField()),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="books", to="libraryApp.author"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
